# SPDX-FileCopyrightText: 2023 Benedikt Bastin
#
# SPDX-License-Identifier: CC0-1.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

  - repo: https://github.com/fsfe/reuse-tool
    rev: v2.1.0
    hooks:
      - id: reuse

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
     - id: fmt
     - id: cargo-check
     - id: clippy

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
