# SPDX-FileCopyrightText: 2024 Benedikt Bastin
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "dyndns"
SPDX-PackageSupplier = "Benedikt Bastin <>"
SPDX-PackageDownloadLocation = "https://github.com/bbastin/dyndns"
annotations = []
